version: '3'
services:
  app:
    image: mcr.microsoft.com/devcontainers/python:0-3.10
    volumes:
      - .:/app
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
      - redis

  redis:
    image: redis:7.0.8
    ports:
      - "6379:6379"